### PR TITLE
`release/4.10.0`

### PR DESCRIPTION
**Pull request by prappo**

### CODE REVIEW

**Review by adamjohnlea — APPROVED** [review]
Works as expected:
`PHP 8.1`
`MySQL 8.0.37`
`WP 6.5.2`

**Comment by spencerfinnell** [comment]
@prappo there are a few Pro-only files in `/src` that need to be removed. I've updated the release doc to note the removals so they aren't distributed to .org.

**Review by spencerfinnell — CHANGES_REQUESTED** [review]
@prappo there are a few Pro-only files in `/src` that need to be removed. I've updated the release doc to note the removals so they aren't distributed to .org.

**Comment by spencerfinnell** [comment]
@prappo something seems to have gone wrong in the PR. The changeset is wrong? https://github.com/awesomemotive/wp-simple-pay-lite/pull/215/files

**Comment by prappo** [comment]
@spencerfinnell Did you mean the empty files? If so not sure why those are empty. 
I've added all the changes using `git add .`

**Comment by spencerfinnell** [comment]
It's only showing 15 changed files -- it doesn't include all of the `4.10.0` changes? 

Screenshot 2024-05-10 at 9 38 53 AM

**Comment by prappo** [comment]
@spencerfinnell this commit https://github.com/awesomemotive/wp-simple-pay-lite/pull/215/commits/2fac101620936babdec4315ae506c06e9e414fee included all the changes from `4.10.0`

**Comment by spencerfinnell** [comment]
@prappo then a lot got reverted in https://github.com/awesomemotive/wp-simple-pay-lite/pull/215/commits/2fac101620936babdec4315ae506c06e9e414fee#diff-26813360af3d2c9b3b1dd06b847cbb438094ddd56844dc304df816437880038f

See that `class-notice-manager.php` in the `release/4.10.0` branch still references PHP 5.6: https://github.com/awesomemotive/wp-simple-pay-lite/blob/release/4.10.0/includes/core/admin/class-notice-manager.php#L57-L61

**Comment by prappo** [comment]
@spencerfinnell , Ok, I will sync with the pro again.

**Comment by spencerfinnell** [comment]
@prappo can you please create a new GitHub release for `4.10.0`?

**Comment by prappo** [comment]
@spencerfinnell sure.

**Pull request merged**
