### PR TITLE
`release/4.8.0`

### PR DESCRIPTION
**Pull request by spencerfinnell**
## [Field Guide →](https://github.com/awesomemotive/wp-simple-pay-pro/wiki/4.8.0-Release)

### CODE REVIEW

**Comment by adamjohnlea** [comment]
@spencerfinnell fresh Lite install, payment button form, no changes, etc. The payment is completed and is recorded in the Stripe Dashboard. However, the Payment Confirmation page (again, default install, no changes to the page, etc.) displays:

CleanShot 2024-02-21 at 13 23 26@2x

**Comment by prappo** [comment]
@spencerfinnell  The payment button becomes uneditable if I add an additional field before publishing the form.

https://github.com/awesomemotive/wp-simple-pay-lite/assets/3511421/bef8959e-b951-4463-b573-a5c091a03a5c

**Comment by prappo** [comment]
@spencerfinnell  This one is available in both lite and pro versions.

Setup-Wizard-‹-beta-1-—-WordPress

**Review by prappo — APPROVED** [review]

**Review by adamjohnlea — APPROVED** [review]
Works as expected
`PHP 8.1.23`
`MySQL 8.0.16`
`WP 6.4.3 `

**Pull request merged**
