### PR TITLE
`release/4.9.0`

### PR DESCRIPTION
**Pull request by spencerfinnell**
### [`stripe-4.9.0-beta-2.zip`](https://github.com/awesomemotive/wp-simple-pay-lite/releases/download/4.9.0-beta-2/stripe-4.9.0-beta-2.zip)

* New: WP Simple Pay is now translated in 10 additional languages.
* New: Do not send a dynamic statement descriptor to Stripe. https://support.stripe.com/questions/statement-descriptor-information
* Fix: Setup Wizard - Ensure "Help Panel" popover is hidden until completion.
* Fix: Blocks - Add block.json for better compatibility.
* Fix: Ensure CAPTCHA Documentation opens in new tab.
* Fix: Admin - Ensure `common.js` WordPress Script is Enqueued.
* Fix: Payment Form - Improve "Invalid Parameters" REST API messaging.
* Fix: Form Builder - Remove "New!" From "Confirmation Page" tab.
* i18n: Various changes for improved translations.
* Dev: Remove legacy action: `simpay_subscription_created` → `simpay_webhook_subscription_created`.
* Dev: Remove legacy action: `simpay_charge_created` → `simpay_webhook_payment_intent_succeeded`.

### CODE REVIEW

**Review by prappo — CHANGES_REQUESTED** [review]
Translation not working

image

**Review by prappo — APPROVED** [review]
@spencerfinnell translation worked after update

**Comment by spencerfinnell** [comment]
@prappo 👍🏻 Lite translations are pulled directly from .org https://translate.wordpress.org/projects/wp-plugins/stripe/ using core WordPress translation functionality so they get cached like normal WordPress updates and may not download right when the language switches.

**Comment by spencerfinnell** [comment]
@prappo you should see Italian working as expected too. The `%1$s` placeholder was fixed in https://translate.wordpress.org/projects/wp-plugins/stripe/stable/it/default/?filters%5Bterm%5D=branding&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

**Review by adamjohnlea — APPROVED** [review]

**Pull request merged**
