### PR TITLE
release/4.4.0 - Sync from Pro `4.1...4.4`

### PR DESCRIPTION
**Pull request by spencerfinnell**
Updates the plugin version number to `4.4.0`.

### CODE REVIEW

**Comment by spencerfinnell** [comment]
@adamjohnlea Still draft while we finalize Pro `4.4`, but if you're able, can you run through some payment form upgrade routines in Lite? Lite hasn't been using the Prices API until this version, so I want to double check things work as expected. Things to look out for when switching from `master` to `sync/pro-440`

- [ ] Payment button works when visiting shortcode directly, outside of wp-admin
- [ ] Payment form price is automatically migrated when editing the payment form settings in wp-admin
- [ ] Payment form amount when filtered with the previous custom amount snippet is migrated correctly:
```php
function simpay_custom_form_157_amount( $amount ) {
	return '123.25';
}
add_filter( 'simpay_form_157_amount', 'simpay_custom_form_157_amount' );
```
- [ ] Editing a payment form's one time amount creates a new price in the Stripe dashboard
- [ ] Editing a payment form's price creates a Checkout Session with the new amount

**Comment by adamjohnlea** [comment]
> Payment form adjusted amount (using old filter method) is migrated correctly
The amount is migrated correctly, but the snippet should no longer work on sync/pro-440, correct?

**Comment by spencerfinnell** [comment]
@adamjohnlea Correct. The migrated amount should be the value of the previous filter, and then to adjust the amount after migration the new version should be used: https://github.com/awesomemotive/wp-simple-pay-snippet-library/blob/master/plugins/custom-amount.php

**Comment by adamjohnlea** [comment]
Then everything worked as it should have

**Pull request closed without merging**
